# Generated by Django 4.2.7 on 2026-05-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('capitale', models.CharField(max_length=100)),
                ('coords_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('coords_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villes', to='public.province')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('type_centre', models.CharField(default='Centre de formation', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centres', to='public.ville')),
            ],
            options={
                'verbose_name': 'Centre de formation',
                'verbose_name_plural': 'Centres de formation',
                'ordering': ['nom'],
            },
        ),
    ]
