# Generated by Django 4.2.7 on 2026-05-13 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0003_create_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN-PRINCIPAL', 'Administrateur Principal'), ('SOUS-ADMIN', 'Sous-Administrateur')], default='SOUS-ADMIN', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('centre', models.ForeignKey(blank=True, help_text='Centre assigné au sous-admin (non utilisé pour admin principal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrateurs', to='public.centre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Administrateur',
                'verbose_name_plural': 'Profils Administrateurs',
                'ordering': ['user__username'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
