# Generated by Django 4.2.7 on 2026-05-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_filiere_module_statutetudiant_supportcours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fichier',
            field=models.FileField(blank=True, help_text="Fichier joint à l'article (PDF, DOC, etc.)", null=True, upload_to='articles/'),
        ),
    ]
