# Generated by Django 4.2.7 on 2026-05-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_article_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='capitale',
        ),
        migrations.RemoveField(
            model_name='province',
            name='code',
        ),
        migrations.RemoveField(
            model_name='province',
            name='coords_latitude',
        ),
        migrations.RemoveField(
            model_name='province',
            name='coords_longitude',
        ),
        migrations.RemoveField(
            model_name='province',
            name='date_creation',
        ),
    ]
